"""Platform resolver config — maps logical URI authorities to runtime targets.

Resolver YAML lives **outside** process Markpacts (generated by marksync or ops).
See ``markpact-contracts/packs/examples/urisys.runtime.resolver.yaml``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any
from urllib.parse import urlsplit, urlunsplit

try:
    import yaml
except Exception:  # pragma: no cover
    yaml = None  # type: ignore[assignment]


def load_resolver_file(path: str | Path) -> dict[str, Any]:
    if yaml is None:  # pragma: no cover
        raise RuntimeError("PyYAML is required to load resolver config.")
    p = Path(path)
    if not p.is_file():
        raise FileNotFoundError(str(p))
    data = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"Resolver config must be a YAML mapping: {p}")
    return data


def apply_resolver_config(runtime: Any, data: dict[str, Any]) -> None:
    """Merge resolver YAML into ``runtime.config`` (targets, environment, runtime defaults)."""
    config = getattr(runtime, "config", None)
    if not isinstance(config, dict):
        runtime.config = {}
        config = runtime.config

    resolver = config.setdefault("resolver", {})
    if data.get("environment"):
        resolver["environment"] = data["environment"]
        config.setdefault("environment", data["environment"])
    if data.get("targets"):
        resolver["targets"] = dict(data["targets"])
        config["targets"] = dict(data["targets"])
    if data.get("uri_aliases"):
        resolver["uri_aliases"] = dict(data["uri_aliases"])
        config["uri_aliases"] = dict(data["uri_aliases"])

    runtime_section = data.get("runtime") or {}
    if runtime_section:
        resolver["runtime"] = dict(runtime_section)
        for key, value in runtime_section.items():
            if key not in config or config[key] in (None, {}):
                config[key] = value
            elif isinstance(config[key], dict) and isinstance(value, dict):
                merged = dict(config[key])
                merged.update(value)
                config[key] = merged


def load_resolver_into_runtime(runtime: Any, path: str | Path) -> dict[str, Any]:
    data = load_resolver_file(path)
    apply_resolver_config(runtime, data)
    return data


def target_profile(config: dict[str, Any], authority: str) -> dict[str, Any] | None:
    targets = (config.get("resolver") or {}).get("targets") or config.get("targets") or {}
    profile = targets.get(authority)
    return dict(profile) if isinstance(profile, dict) else None


def apply_uri_aliases(uri: str, config: dict[str, Any]) -> str:
    """Remap domain URIs (e.g. ``package://chromium/...``) via resolver aliases."""
    resolver = config.get("resolver") or {}
    aliases = config.get("uri_aliases") or resolver.get("uri_aliases") or {}
    if not isinstance(aliases, dict) or not aliases:
        return uri
    exact = aliases.get(uri)
    if isinstance(exact, str) and exact:
        return exact
    for prefix, replacement in sorted(aliases.items(), key=lambda item: -len(str(item[0]))):
        prefix_s = str(prefix)
        repl = str(replacement)
        if uri.startswith(prefix_s):
            suffix = uri[len(prefix_s) :]
            return f"{repl}{suffix}"
    return uri


def resolve_uri(uri: str, config: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    """Return URI (optionally rewritten) and extra call context from target profile."""
    uri = apply_uri_aliases(uri, config)
    parts = urlsplit(uri)
    authority = parts.netloc
    if not authority:
        return uri, {}

    profile = target_profile(config, authority)
    if not profile:
        return uri, {}

    extra: dict[str, Any] = {
        "target": authority,
        "target_profile": profile,
    }

    remap = profile.get("uri_host") or profile.get("host")
    if remap and str(remap) != authority:
        uri = urlunsplit((parts.scheme, str(remap), parts.path, parts.query, parts.fragment))

    transport = profile.get("transport")
    if transport:
        extra["transport"] = transport

    return uri, extra


__all__ = [
    "apply_resolver_config",
    "apply_uri_aliases",
    "load_resolver_file",
    "load_resolver_into_runtime",
    "resolve_uri",
    "target_profile",
]
