flowchart TD
%% generated in 0.00s
    core__node["core.node<br/>1 funcs"]
    core__php["core.php<br/>1 funcs"]
    core__python["core.python<br/>119 funcs"]
    examples__packs["examples.packs<br/>4 funcs"]
